version: "3.9"
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
  my-node-app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_HOST=mongodb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - DB_PORT=27017
      - BATCHING_SIZE=100
      - CSV_IMPORT_DELIMITER=,
      - CSV_IMPORT_URI=https://api.frw.co.uk/feeds/all_listings.csv
